name: Update Tracks List

on:
  push:
    paths:
      - 'src/tracks/**'  # Изменили путь

jobs:
  update-tracks:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Pull latest changes
        run: git pull
      
      - name: Generate tracks.json
        run: |
          echo '[' > tracks.json
          
          find src/tracks -type f \( -iname "*.mp3" -o -iname "*.wav" \) | while read -r file; do
            filename=$(basename "$file")
            name="${filename%.*}"
            name=$(echo "$name" | sed -e 's/[\\\/\:\*\?\"\<\>\|]/_/g')
            echo "  {\"name\": \"$name\", \"src\": \"$file\"}," >> tracks.json
          done
          
          sed -i '$ s/,$//' tracks.json
          echo ']' >> tracks.json
          
          jq . tracks.json > temp.json && mv temp.json tracks.json
          
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tracks.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update tracks.json"
          git push
